language: cpp
addons:
    apt:
        packages:
            - libpng-dev
            - cmake
            - qmake
              # libdsk-dev      # not available
script:
    - pushd hideur_maikeur && make && popd
    - pushd gfx2crtc && make && popd
    - pushd iDSK && cmake . && make && popd
    - pushd libstsound && ./build_config.sh && ./configure && make && popd
      # pushd Reloaded && cmake . && make && popd     # needs CMake 3.1.0
      # pushd DiskSwissKnife && qmake && make && popd # needs qhexedit
      # pushd font_catcher && make && popd            # needs libmagickpp
      # pushd cpctools && cmake . && make && popd     # needs libdsk
