language: cpp
sudo: true
addons:
    apt:
        packages:
            - libpng-dev
            - cmake
            - qt4-qmake
            - libmagick++-dev
            - libwxgtk3.0-dev
            - portaudio19-dev
              # libdsk-dev      # not available
script:
      # pushd Reloaded && cmake . && make && popd     # needs stsoundlibrary
    - pushd font_catcher && make && popd
      # pushd DiskSwissKnife && qmake && make && popd # needs qhexedit
      # pushd cpctools && cmake . && make && popd     # needs libdsk
