os: Visual Studio 2019
clone_folder: c:\projects\cpctools
platform: x86
configuration: Release

environment:
    libdskdir: "C:/projects/cpctools/libdsk"

install:
    - ps: |
        Start-FileDownload "https://github.com/cpcsdk/libdsk/releases/download/v1.5.12/libdsk-win32-1.5.12.zip"
        7z x libdsk-win32-1.5.12.zip -o"$($env:libdskdir)"

build:
    project: build/INSTALL.vcxproj

before_build:
    - cd c:\projects\cpctools
    - mkdir -p build
    - cd build
    - cmake -G "Visual Studio 14 2015" ../cpctools -D LIBDSK_HEADERS_DIR="%libdskdir%/include" -D LIBDSK_LIB_DIR="%libdskdir%/win32vc6/Release"

after_build:
    - 7z a cpctools.zip ./tools/AFT2/Release/aft2.exe ./lib/Release/cpc.dll ./tools/cpcfs/Release/cpcfs.exe ./tools/damsConverter/Release/damsConverter.exe ./tools/dataLinker/Release/dataLinker.exe ./tools/Release/*.exe %libdskdir%/win32vc6/Release/libdsk.dll

artifacts:
    - path: "build/cpctools.zip"
      name: "CPCTools win32"
